src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/init_type_error.aes
test/contracts/missing_state_type.aes

- [PT-163053747](https://www.pivotaltracker.com/story/show/163053747)

PT-163053747 Add missing type check of init function

---

src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/missing_fields_in_record_expression.aes

[PT-163146461](https://www.pivotaltracker.com/story/show/163146461)

PT-163146461 Check for missing fields in record expressions

---

src/aeso_builtins.erl

https://www.pivotaltracker.com/story/show/163146624

PT-163146624 Improve builtins

---

rebar.config
rebar.lock
src/aeso_abi.erl
src/aeso_blake2.erl
test/aeso_blake2_tests.erl

This removes the dependency on enacl, and NIFs.

Add Erlang implementation of Blake2B

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_icode.erl

And fix the return type of String.sha3

Add Crypto.ecverify

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_icode.erl

Pivotal: [PT-163362624](https://www.pivotaltracker.com/story/show/163362624)
Protocol: https://github.com/aeternity/protocol/pull/294
Bytecode: https://github.com/aeternity/aebytecode/pull/3
Aeternity: https://github.com/aeternity/aeternity/pull/2039
Ready to merge.

PT-163362624 generic hash functions

---

src/aeso_builtins.erl

Adding SafeMath to VM_AEVM_SOPHIA_2 will break String.concat otherwise.

Refactor String.concat to not shift 256 bits

---

.gitignore
README.md
src/aeso_ast.erl
src/aeso_compiler.erl
test/aeso_compiler_tests.erl

Clean up the interface to the sophia compiler.
[PT-163063316](https://www.pivotaltracker.com/story/show/163063316)

PT-163063316 Interface to sophia

---

src/aeso_ast_infer_types.erl
src/aeso_ast_to_icode.erl
src/aeso_builtins.erl
src/aeso_icode.erl
src/aeso_parser.erl
src/aeso_pretty.erl
src/aeso_scan.erl
src/aeso_syntax.erl
test/contracts/all_syntax.aes
test/contracts/multi_sig.aes
test/contracts/operators.aes

Replaces bit arithmetic operations with a builtin `bits` type.

PT-163478903 builtin bits type

---

src/aeso_abi.erl
src/aeso_compiler.erl
src/aeso_pretty.erl

OTP-21 dialyzer is more diligent about type specs and uncovered some bad ones.

Fix incorrect type specs

---

.circleci/config.yml

Blocked by https://github.com/aeternity/docker-builder/pull/12
PT: https://www.pivotaltracker.com/story/show/163053596

Initial CircleCI integration

---

.circleci/config.yml
rebar.config
rebar.lock
src/aeso_abi.erl
src/aeso_blake2.erl
src/aeso_compiler.erl
src/aeso_pretty.erl
src/aesophia.app.src
src/aesophia.erl
test/aeso_blake2_tests.erl

A simple standalone compiler (as escript). It can dump the resulting Erlang map to a file (using `term_to_binary()`. This is required by - https://www.pivotaltracker.com/story/show/163553535

Roma standalone

---

src/aeso_ast_infer_types.erl
src/aeso_compiler.erl
src/aeso_pretty.erl
test/aeso_abi_tests.erl

To be used by some swanky compiler HTTP endpoint.

Add function to decode VM values to Sophia abstract syntax

---

src/aeso_abi.erl
src/aeso_compiler.erl
test/aeso_abi_tests.erl

Making the calldata creation and call result decoding easier to use.

To sophia value revisited

---

README.md
docs/aeso_aci.md
rebar.config
rebar.lock
src/aeso_aci.erl
src/aeso_ast.erl
src/aesophia.app.src
test/aeso_aci_tests.erl
test/aeso_eunit_SUITE.erl

Add an ACI generator to the compiler.

New aci generator

---

rebar.config
rebar.lock

https://www.pivotaltracker.com/story/show/164595944

Use latest aebytecode

---

rebar.config

To amend the comment in https://github.com/aeternity/aeternity/pull/2243#discussion_r265613319

Check that VERSION file exists

---

src/aeso_aci.erl

In scope of https://www.pivotaltracker.com/story/show/164834227

Fix build warning

---

rebar.config
rebar.lock

Pt 164597736 variant types

---

rebar.config

New version of aebytecode available

Update commit hash aebytecode

---

rebar.config
rebar.lock
src/aeso_aci.erl
src/aeso_ast_infer_types.erl
src/aeso_ast_to_icode.erl
src/aeso_compiler.erl
src/aeso_parser.erl
src/aeso_pretty.erl
src/aeso_scan.erl
src/aeso_syntax.erl
test/aeso_abi_tests.erl
test/aeso_compiler_tests.erl
test/aeso_scan_tests.erl
test/contracts/address_literals.aes
test/contracts/bad_address_literals.aes
test/contracts/bitcoin_auth.aes
test/contracts/fundme.aes

hash -> bytes(32)
signature -> bytes(64)
address literals

Add bytes(int), add address_literalsm add ecverify_secp256k1

---

src/aeso_ast_to_icode.erl
test/aeso_compiler_tests.erl
test/contracts/bytes_equality.aes

[PT-165597438](https://www.pivotaltracker.com/story/show/165597438)

Support equality on bytes(N)

---

rebar.config
rebar.lock
src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/165857097

Add value and gas to remote calls

---

src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/165857097

Add call value instruction in fate

---

src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/type_errors.aes

[PT-159592825](https://www.pivotaltracker.com/story/show/159592825)

Check for repeated argument names to functions

---

src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/165964555

Keep the contract type in fate code

---

rebar.config
rebar.lock
src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/166148534

Pt 166148534 refactor fate code

---

src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/162805991

The state is always live to prevent bad optimizations

---

rebar.config
rebar.lock
src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/166282300

Add missing instructions for FATE

---

rebar.config
rebar.lock
src/aeso_ast_to_fcode.erl
src/aeso_compiler.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl

Update to new TUPLE instruction

---

src/aeso_fcode_to_fate.erl

Fix bug in basic block generation

---

rebar.config
rebar.lock
src/aeso_ast_to_fcode.erl
src/aeso_compiler.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl

Also add `contract_to_address` and make fate compiler backend also return a `map`.

Fate crypto ops

---

rebar.config
rebar.lock
src/aeso_ast_to_icode.erl
src/aeso_compiler.erl
src/aeso_icode_to_asm.erl

Pt 166602172 create calldata fate

---

src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_builtins.erl
test/contracts/aeproof.aes
test/contracts/basic_auth.aes
test/contracts/bitcoin_auth.aes
test/contracts/dutch_auction.aes
test/contracts/erc20_token.aes
test/contracts/fundme.aes
test/contracts/oracles.aes
test/contracts/oracles_gas.aes
test/contracts/oracles_no_vm.aes
test/contracts/variant_types.aes

https://www.pivotaltracker.com/story/show/166694614

Add require builtin

---

rebar.config
rebar.lock
src/aeso_ast_to_fcode.erl
src/aeso_fcode_to_fate.erl
test/aeso_calldata_tests.erl
test/aeso_compiler_tests.erl

Add Auth.tx_hash + fix create_calldata remains from @ThomasArts PR...

Pt 164629640 auth tx hash for FATE

---

rebar.config
rebar.lock
src/aeso_ast_to_fcode.erl
src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/166786424

Add type information to oracle instructions

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_builtins.erl
src/aeso_fcode_to_fate.erl
src/aeso_pretty.erl
src/aeso_syntax.erl
test/aeso_compiler_tests.erl
test/contracts/bytes_to_x.aes

~~Waiting for https://github.com/aeternity/aebytecode/pull/57~~

Add Bytes.to_int and Bytes.to_str

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_builtins.erl
src/aeso_fcode_to_fate.erl
src/aeso_pretty.erl
test/aeso_compiler_tests.erl
test/contracts/events.aes

PT-166233670 FATE events

---

rebar.config
rebar.lock
src/aeso_ast_to_fcode.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl
test/contracts/aens.aes

https://www.pivotaltracker.com/story/show/166233700

Implement aens instructions for fate

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_icode.erl
test/contracts/aens.aes

https://www.pivotaltracker.com/story/show/166927306

Use a name string rather than a name hash in transfer and revoke

---

src/aeso_fcode_to_fate.erl

https://www.pivotaltracker.com/story/show/166868668

Use EXIT for internal errors to burn all gas

---

src/aeso_compiler.erl

https://www.pivotaltracker.com/story/show/166868668

Properly decode revert strings for fate as well

---

src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_compiler.erl
test/aeso_calldata_tests.erl
test/contracts/stub.aes

Make sure that we can generate calldata (and decode calldata) using ACI-stubs.

PT-166731397 Add compiler backend

---

.gitignore
rebar.config
rebar.lock
src/aeso_compiler.erl

Add abi_version to compiler result

Pt 167126818

---

CHANGELOG.md
rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_compiler.erl
src/aeso_fcode_to_fate.erl
src/aeso_parser.erl

Ref [PT-16780529](https://www.pivotaltracker.com/story/show/167805291)
Merge order:
1. PR for aebytecode: https://github.com/aeternity/aebytecode/pull/64
2. this PR
3. PR for aeternity: https://github.com/aeternity/aeternity/pull/2638

[PT-167805291] Add opcode for ecrecover

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_fcode_to_fate.erl
test/aeso_calldata_tests.erl
test/contracts/basic_auth.aes
test/contracts/bitcoin_auth.aes

Needs https://github.com/aeternity/aebytecode/pull/70

PT-167996886 A proper ecverify

---

src/aeso_fcode_to_fate.erl

Check tests in https://github.com/aeternity/aeternity/pull/2701

Fate compiler optimizations

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
test/contracts/complex_types.aes
test/contracts/local_poly_fail.aes
test/contracts/test.aes
test/contracts/tuple_match.aes

- [PT-168026330](https://www.pivotaltracker.com/story/show/168026330)
- [PT-166785003](https://www.pivotaltracker.com/story/show/166785003)
- [PT-166786491](https://www.pivotaltracker.com/story/show/166786491)
- [PT-168216899](https://www.pivotaltracker.com/story/show/168216899)
Enforces
- No higher-order entrypoints
- No polymorphic entrypoints (AEVM only)
- No polymorphic or higher-order oracles or `AENS.resolve` calls

Polymorphism checks

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_compiler.erl
src/aeso_fcode_to_fate.erl
test/aeso_abi_tests.erl

Needs https://github.com/aeternity/aebytecode/pull/75

No calls to init-function (except when creating contract)

---

src/aeso_ast_to_icode.erl
src/aeso_icode.erl

Why didn't anybody notice it before?

Added chars in AEVM

---

rebar.config
rebar.lock
src/aeso_compiler.erl
src/aeso_errors.erl
test/aeso_abi_tests.erl
test/aeso_compiler_tests.erl

Minor updates to error printing.
`aebytecode` commit only because it was lagging behind `master`.

Minor error printing

---

src/aeso_ast_to_icode.erl
src/aeso_builtins.erl

The corresponding change for FATE is here: https://github.com/aeternity/aeternity/pull/2754

[AEVM] Compile Crypto.(hash_fun) to String.(hash_fun) for byte arrays

---

src/aeso_ast_infer_types.erl

... if under a lambda or switch.

Fix bug with missing fields causing compiler crash

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl
test/contracts/address_literals.aes
test/contracts/bad_address_literals.aes

Casts an address to a (any) contract type.

Add Address.to_contract

---

src/aeso_ast_infer_types.erl

Fix not instantiated uvar

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Nearly there - let's wait for some more testing efforts

Prepare release - v4.0.0

---

src/aeso_parser.erl

Add stdlib include handling when inside an escript

---

src/aeso_compiler.erl
test/aeso_compiler_tests.erl
test/contracts/validation_test1.aes
test/contracts/validation_test2.aes
test/contracts/validation_test3.aes

Compiler part of GH-172
- aesophia_cli: aeternity/aesophia_cli#27
- aesophia_http: aeternity/aesophia_http#49

Add function to validate byte code against source code

---

src/aeso_compiler.erl
src/aeso_fcode_to_fate.erl
src/aeso_vm_decode.erl
test/aeso_abi_tests.erl
test/aeso_calldata_tests.erl

Handle encoding/decoding bits

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

GH-181 Prepare 4.1.0-rc1

---

priv/stdlib/BLS12_381.aes
rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl
test/contracts/pairing_crypto.aes

Depends on https://github.com/aeternity/aebytecode/pull/88

Add BLS12-381 operations (to FATE)

---

src/aeso_ast_infer_types.erl
src/aeso_parser.erl
src/aeso_syntax.erl
test/aeso_compiler_tests.erl
test/contracts/bad_records.aes

Fix parse errors causing crashes instead of nice errors

---

src/aeso_ast_infer_types.erl
src/aeso_parser.erl
test/aeso_compiler_tests.erl
test/contracts/qualified_constructor.aes

Missing cases in parser and type checker for qualified constructors

Handle qualified constructors in patterns

---

CHANGELOG.md
src/aeso_aci.erl
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_compiler.erl
src/aeso_parser.erl
src/aeso_pretty.erl
src/aeso_syntax.erl
src/aeso_syntax_utils.erl
test/aeso_compiler_tests.erl
test/aeso_parser_tests.erl
test/contracts/factorial.aes
test/contracts/lhs_matching.aes
test/contracts/stack.aes

Fixes GH-196
Some examples:
```sophia
function from_some(Some(x)) = x
function
length : list('a) => int
length([])      = 0
length(_ :: xs) = 1 + length(xs)
function
append([], ys)      = ys
append(x :: xs, ys) = x :: append(xs, ys)
```

GH-196 pattern matching lhs

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Prepare release 4.2.0

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl
test/contracts/aens_update.aes
test/contracts/channel_on_chain_contract_oracle.aes
test/contracts/unapplied_builtins.aes

Fixes #188 and #179 
~Needs https://github.com/aeternity/aebytecode/pull/89 to go in first.~

Add AENS.lookup and Oracle.expiry

---

priv/stdlib/List.aes
priv/stdlib/Option.aes

Tail recursion is not always as rewarding as in xkcd commics. Changed functions have about 2 times less gas usage

Optimize stdlib

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_fcode_to_fate.erl
test/aeso_compiler_tests.erl
test/contracts/basic_auth_tx.aes

Needs https://github.com/aeternity/aebytecode/pull/90
This is the compiler part of #202

Gh 202 auth tx introspection

---

priv/stdlib/Frac.aes

Rational numbers library - Frac.aes

---

src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/bad_number_of_args.aes

Instant unification error on arguments count mismatch

---

priv/stdlib/String.aes

+ add String.concats as an additional convenience function.

Add some comments to String.aes

---

rebar.config
rebar.lock
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_ast_to_icode.erl
src/aeso_fcode_to_fate.erl
src/aeso_pretty.erl
test/aeso_compiler_tests.erl
test/contracts/bad_protected_call.aes
test/contracts/protected_call.aes

- Issue: aeternity/aesophia#203
- aeternity/aebytecode#93
- aeternity/aeternity#3162
- aeternity/protocol#467

Add support for protected contract calls

---

CHANGELOG.md
src/aeso_aci.erl

Fixes aeternity/aesophia_http#59

Handle negative numbers in aci

---

priv/stdlib/Frac.aes

There were some bugs in the optimizer. Also added better error messages. I found functions `one` and `zero` extremely useful in practice.

Enchanted Frac library a bit

---

docs/sophia.md
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_compiler.erl
src/aeso_parser.erl
src/aeso_pretty.erl
src/aeso_syntax.erl
src/aeso_syntax_utils.erl
test/aeso_compiler_tests.erl
test/contracts/05_greeter.aes
test/contracts/all_syntax.aes
test/contracts/bad_arity.aes
test/contracts/bad_unnamed_map_update_default.aes
test/contracts/empty_typedecl.aes
test/contracts/higher_kinded_type.aes
test/contracts/multi_sig.aes
test/contracts/non_functional_entrypoint.aes
test/contracts/not_toplevel_contract.aes
test/contracts/not_toplevel_include.aes
test/contracts/not_toplevel_namespace.aes
test/contracts/toplevel_let.aes
test/contracts/voting.aes

fixes #246 
fixes #244 
fixes #243 
fixes #242 
fixes #252

Fix error messages for some illegal constructions, fix absolute path includes

---

docs/sophia.md

Fixed example

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Yeah, I forgot about these last time

Version push – 4.3.0

---

src/aeso_ast_infer_types.erl
src/aeso_syntax.erl
test/aeso_compiler_tests.erl
test/contracts/bad_function_block.aes

Ban empty contracts, ban function blocks with mismatched declarations

---

priv/stdlib/Option.aes

Yeah, Sophia is not lazy
fixes #266

Fixed `force` function

---

src/aeso_vm_decode.erl
test/aeso_calldata_tests.erl
test/contracts/funargs.aes

Fix singleton record calldata decode + test

---

src/aeso_compiler.erl

This small fix reduces the runtime of the eunit test suite on my computer from 38s to 22s. Encoding call data for the hyperchain staking contact(https://github.com/aeternity/hyperchains-contract/) improved by 35%(average of 100 runs).
My measurements indicate that parsing contributes to 42% of the overall runtime during compilation.
The code might be optimized further.

Improve call data encoding times by 35%

---

src/aeso_aci.erl
src/aeso_ast_infer_types.erl
src/aeso_compiler.erl
test/aeso_aci_tests.erl

Hyperchains will be governed by a Sophia smart contract which needs to be called pretty often. Calling the compiler to encode/decode the call data for this smart contract is infeasible because it would introduce a nasty bottleneck in block validation/sync time. Creating an hard coded encoder/decoder for a particular contract would be inelegant and inflexible. The solution we agreed on in the HC team is to create an erlang library which given a particular json ACI creates an encoder/decoder for you(or does the encoding/decoding for you).
In order to test the upcoming helper library we will:
- Refactor the existing core node test suite to use the ACI library
- Introduce tests in the compiler which test compatibility of encoding/decoding call data between the compiler and library
As the core …

Provide the ACI along with the bytecode

---

docs/sophia_stdlib.md

Document the resolution of https://github.com/aeternity/aeternity/issues/3002
NOTE: This PR goes to `master`

Document Chain.block_hash at current height

---

README.md
docs/sophia.md
docs/sophia_stdlib.md
priv/stdlib/List.aes
priv/stdlib/Option.aes
src/aeso_aci.erl
src/aeso_ast_infer_types.erl
src/aeso_compiler.erl
src/aeso_syntax.erl
src/aeso_vm_decode.erl
test/aeso_aci_tests.erl
test/aeso_calldata_tests.erl
test/aeso_compiler_tests.erl
test/contracts/bad_function_block.aes
test/contracts/funargs.aes
test/contracts/hermetization_turnoff.aes

Lima master merge

---

src/aeso_ast_infer_types.erl

Enforced ordering of constraint ETS tables (by insertion time). Previous implementation was giving different results depending on tables implementations (try running eunit on OTP23 for example). Moreover, in some circumstances the compilation could fail due to this inconsistency.

Fix constraints ordering

---

src/aeso_parse_lib.erl

This patch should nicely reduce stack usage of the parser

Trampoline in parser

---

src/aeso_ast_to_fcode.erl
test/aeso_compiler_tests.erl
test/contracts/child_contract_init_bug.aes

Fix #324: bug when compiling default init in the presence of child contracts

---

CHANGELOG.md
docs/sophia_stdlib.md
priv/stdlib/Set.aes

Implement `Set` stdlib

---

CHANGELOG.md
docs/sophia_features.md
src/aeso_ast_infer_types.erl
src/aeso_parser.erl
src/aeso_scan.erl
src/aeso_syntax.erl
test/aeso_compiler_tests.erl
test/contracts/using_namespace.aes
test/contracts/using_namespace_ambiguous_name.aes
test/contracts/using_namespace_hidden_parts.aes
test/contracts/using_namespace_undefined.aes
test/contracts/using_namespace_undefined_parts.aes
test/contracts/using_namespace_wrong_scope.aes

Implement loading namespaces with the `using` keyword

---

CHANGELOG.md
src/aeso_aci.erl
test/aeso_aci_tests.erl

Don't forget stateful when rendering the ACI

---

docs/sophia_features.md

Clarify documentation on protected calls

---

src/aeso_fcode_to_fate.erl

Implement caching for compiled child contracts

---

docs/sophia_stdlib.md

Clarify signature format for ecverify/ecrecover

---

CHANGELOG.md
src/aeso_ast_to_fcode.erl
test/aeso_compiler_tests.erl
test/contracts/polymorphism_chain_create.aes
test/contracts/polymorphism_variance_switching_chain_create.aes
test/contracts/polymorphism_variance_switching_chain_create_fail.aes

Fix: Get the type of Chain.create() from its application

---

src/aeso_ast_infer_types.erl
src/aeso_syntax.erl
test/aeso_compiler_tests.erl
test/contracts/polymorphism_variance_switching_unify_with_interface_decls.aes
test/contracts/polymorphism_variance_switching_void_supertype.aes

Fixes: #413
This introduces a couple of fixes for the referenced issue.
The commits should be merged without squashing.

Polymorphism fixes

---

docs/aeso_compiler.md
rebar.config
rebar.lock
src/aeso_fcode_to_fate.erl

Include all functions in the symbols map

---

CHANGELOG.md
src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/complex_types.aes
test/contracts/environment.aes
test/contracts/resolve_field_constraint_by_arity.aes
test/contracts/spend_test.aes

Allow calling a different instance of the current contract

---

CHANGELOG.md
src/aeso_ast_infer_types.erl
src/aeso_pretty.erl
test/aeso_compiler_tests.erl
test/contracts/var_args_unify_fun_call.aes
test/contracts/var_args_unify_let.aes

Ban the unification of uvars and var_args functions

---

CHANGELOG.md
docs/sophia_stdlib.md
priv/stdlib/AENSCompat.aes
src/aeso_ast_infer_types.erl
src/aeso_ast_to_fcode.erl
src/aeso_vm_decode.erl
test/aeso_compiler_tests.erl
test/contracts/aens.aes
test/contracts/aens_update.aes
test/contracts/bad_aens_resolve.aes
test/contracts/bad_aens_resolve_using.aes
test/contracts/polymorphic_aens_resolve.aes
test/contracts/unapplied_builtins.aes

Introduce AENSv2 namespace to introduce raw data pointers

---

CHANGELOG.md
src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/calling_child_contract_entrypoint.aes
test/contracts/using_contract_as_namespace.aes

Ban using contracts as namespaces

---

docs/sophia_stdlib.md

add clarification for Chain.timestamp

add clarification for Chain.timestamp

---

CHANGELOG.md
src/aeso_ast_infer_types.erl
test/contracts/warnings.aes

Hide warning when calling with non-0 value arg

---

.github/workflows/requirements.txt

nothing urgent. but as I updated again in protocol repo I thought it is good to update everywhere

chore(deps): mkdocs version update

---

docs/sophia_features.md

Fix markup in sophia_features.md

---

CHANGELOG.md
src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/warning_unused_include_no_include.aes

Mark only included files as potentially unused

---

docs/sophia_stdlib.md

Relates to aeternity/aeternity#4080 and aeternity/aeternity#4105

[Ceres]: Document wildcard AENS delegation signatures

---

CHANGELOG.md
src/aeso_compiler.erl

A PR using the API in `aesophia_cli` is already in progress...

Introduce API to encode/decode Sophia value to/from FATE

---

docs/sophia_stdlib.md

fix AENS.update stdlib doc

---

docs/sophia_stdlib.md

Document Chain.spend and sort Chain functions

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Prepare v7.3.0 release

---

CHANGELOG.md
docs/sophia_stdlib.md
src/aeso_ast_infer_types.erl
test/contracts/unapplied_builtins.aes

[Ceres] Allow arbitrary sized message in Crypto.verify_sig

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Prepare release v7.4.0

---

CHANGELOG.md
docs/sophia_features.md
src/aeso_compiler.erl
src/aeso_parse_lib.erl
src/aeso_parser.erl
src/aeso_utils.erl
test/aeso_compiler_tests.erl
test/contracts/dir1/bar.aes
test/contracts/dir2/baz.aes
test/contracts/relative_include.aes

Improve resolution of relative includes

---

.gitignore
CHANGELOG.md
src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/warning_used_record_typedef.aes

Disable unused type warnings for type used inside of records

---

.github/workflows/requirements.txt

Bump pygments version

---

docs/sophia_features.md
docs/sophia_stdlib.md

[Ceres]: Update delegation signature documentation

---

CHANGELOG.md
src/aeso_fcode_to_fate.erl
src/aeso_vm_decode.erl
test/aeso_calldata_tests.erl
test/contracts/funargs.aes

[Ceres] Handle Bytes.to_any_size in calldata

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Prepare release v4.7.1

---

docs/sophia_features.md

Fix Typo and whitespace in sophia_features.md

---

CHANGELOG.md
rebar.config
src/aesophia.app.src

Prepare release v8.0.0

---

docs/sophia_stdlib.md

This PR is supported by Aeternity Foundation.

Docs: fix error in List.partition description

---

docs/sophia_features.md
docs/sophia_stdlib.md

Clarify you need to include some standard library functions/modules

---

src/aeso_ast_infer_types.erl
test/aeso_compiler_tests.erl
test/contracts/delayed_field_constraint_bug.aes

Fixes a bug that was mentioned by @hanssv on Slack. The test in this PR was failing to compile.

Try to solve more field constraints before solve all constraints
