aeternity/aesophia

src/aesophia.app.src
For next Roma release we want to point to this version of the compiler (not consensus breaking, but small changes)
=> Bump version

src/aeso_compiler.erl
Remove the explicit handling of filename extension ".aes".
And take the chance to make file handling errors ahve the same format
as other errors.
=> Remove specific filename extension handling

README.md, docs/aeso_compiler.md
Move the module documentation out of the README into separate files in the docs directory.
=> Move module documentation to separate files

src/aeso_ast_infer_types.erl, src/aeso_compiler.erl, src/aeso_parser.erl, src/aeso_pretty.erl, test/aeso_abi_tests.erl
There was a bug in the handling of oracles and oracle queries when building calldata
=> Fix calldata creation for contracts involving oracles

rebar.config, rebar.lock, src/aeso_ast_infer_types.erl, src/aeso_ast_to_icode.erl, test/aeso_compiler_tests.erl, test/contracts/basic_auth.aes
Adds a new "builtin" namespace `Auth` that (at the moment) has one member `tx_hash`. `Auth.tx_hash` returns a `option(hash)` where `Some(hash)` is returned in Generalized account's authentication context, and `none` otherwise.
Since we have no good mechanism for "hiding" new features - apart from keeping a feature branch - let's merge this. If nothing else it will stop people from using the soon to be reserved namespace `Auth` :-)
=> Add Auth.tx_hash - namespace + primop

rebar.config, rebar.lock, src/aeso_ast_to_icode.erl, src/aeso_compiler.erl
For backwards compatibility (mainly in primops) it isn't a great idea to introduce a new VM-type. Instead, encode `bytes(N)` as either `word` or `{tuple, [word,...]}`.
=> Revert bytes(N) from icode/vm-types

src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_ast_to_icode.erl, src/aeso_fcode_to_fate.erl, src/aeso_parser.erl, src/aeso_pretty.erl, src/aeso_scan.erl, src/aeso_syntax.erl, src/aeso_syntax_utils.erl, test/aeso_compiler_tests.erl, test/aeso_scan_tests.erl, test/contracts/all_syntax.aes, test/contracts/functions.aes
Removes `let rec` from the language, and fixes type checking and compilation of `let fun`. Supersedes #58.
=> Letrec and letfun

CHANGELOG.md, docs/aeso_aci.md, src/aeso_aci.erl, src/aeso_ast_infer_types.erl, src/aeso_compiler.erl, src/aeso_syntax_utils.erl, test/aeso_abi_tests.erl, test/aeso_aci_tests.erl, test/aeso_compiler_tests.erl, test/contracts/bad_events.aes, test/contracts/bad_events2.aes
- Keyword `indexed` is now optional for word typed (`bool`, `int`, `address`,
...) event arguments.
- State variable pretty printing now produce `'a, 'b, ...` instead of `'1, '2, ...`.
- ACI is restructured and improved:
- `state` and `event` types (if present) now appear at the top level.
- Namespaces and remote interfaces are no longer ignored.
- All type definitions are included in the interface rendering.
- API functions are renamed, new functions are `contract_interface`
and `render_aci_json`.
=> Restructure and improve ACI

src/aeso_ast_to_icode.erl
I have found that function `builtin_call` is not used in some places where it should be
=> Popularized use of builtin_call function

src/aeso_compiler.erl, test/aeso_abi_tests.erl
A small oversight in `create_calldata`/`to_sophia_value`...
=> Allow negative literals in calldata and result

rebar.config, rebar.lock, src/aeso_ast_to_fcode.erl, src/aeso_fcode_to_fate.erl, test/aeso_compiler_tests.erl
Keep oracle type information on fcode level
Introduce typereps as values
Handle oracle registration
Handle oracle query object and oracle_query op
Handle oracle get question
Handle oracle query fee
Handle oracle get answer
Handle oracle respond
Handle oracle extend
=> Handle oracle operation in FATE

src/aeso_ast_to_fcode.erl
Due to bad `fsplit_pat` construction the following contract
```
contract XD =
entrypoint tuplify3() = (t) => switch(t)
(x, y, z) => 3
```
used not to compile
=> Fix split_pat

src/aeso_ast_infer_types.erl
`require` function could be used to exploit type system, because it was returning `'a` type instead of `()`:
bug copyright (c) Martin Grigorov
```
contract Identity =
type state = ()
entrypoint main(x : int) = x
entrypoint sum(a: int, b: int) = a + b
entrypoint test_sum_correct() =
let result = 5
require(sum(2,3)== 5, "Result of sum is incorrect!")
```
=> Changed 'require' function return type to Unit

src/aeso_ast_to_fcode.erl, test/aeso_compiler_tests.erl, test/contracts/tuple_match.aes
Pretty printing was broken in few places due to type errors – one may check it by executing `pp_fexpr` on bodies of functions right after processing. There were also some bugs in managing patterns (`fpat` was sometimes mistaken with `fsplit_pat`). I have added one test that used to crash previous version.
Beside that I undo #106 because the "fix" I provided there turned out to be treatment of symptoms. This PR should fix that issue in proper way now.
=> Fixed pretty printing and pattern split

src/aeso_aci.erl, src/aeso_ast_infer_types.erl, src/aeso_parser.erl, src/aeso_pretty.erl, test/aeso_abi_tests.erl, test/aeso_aci_tests.erl, test/aeso_compiler_tests.erl, test/contracts/abort_test.aes, test/contracts/abort_test_int.aes, test/contracts/address_chain.aes, test/contracts/address_literals.aes, test/contracts/aens.aes, test/contracts/all_syntax.aes, test/contracts/bad_address_literals.aes, test/contracts/complex_types.aes, test/contracts/events.aes, test/contracts/funargs.aes, test/contracts/maps.aes, test/contracts/modifier_checks.aes, test/contracts/oracles.aes, test/contracts/oracles_no_vm.aes, test/contracts/remote_call.aes, test/contracts/state_handling.aes, test/contracts/stateful.aes, test/contracts/voting.aes
Previously the syntax for tuple types was identical to tuple values:
```pascal
x : () // unit
y : (int) // actually an int, not a tuple
z : (int, string) // pair
``` 
Problem with this notation is that it is shared with multi argument function domain which causes
```pascal
f : (int, int) => int
```
to mean both a function that takes two ints as an argument **and** a function that takes a single _pair_ of ints. Our parser forbids ambiguous parsing results and takes strategy to parse domain as a tuple and turn it into an argument list which makes having a tuple or unit as the only argument impossible. Tricks like `((int, int)) => int` do not work, because `((int, int))` is parsed literally as `(int, int)` which is treated at first as a tuple and then...
```erlang
%% TODO: not nice …
```
=> Change tuple typing syntax

src/aeso_ast_to_icode.erl
Because `qid` was not accepted as a typefunction the following code 
```
contract Test = 
datatype myOption('a) = MyNone | MySome('a)
entrypoint optionFn(v: myOption(string)): myOption(string) = v
```
Used to lead to `function_clause` error.
Bug copyright (c) @nduchak
=> Covered qid case in ast_typerep

src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_fcode_to_fate.erl
[PT-167701356](https://www.pivotaltracker.com/story/show/167701356)
Change compilation of the `init` function in FATE. Now generates a new function `INIT` that writes the state instead of returning it. The create contract transaction calls this function instead of `init` (unbeknownst to the user; the calldata still has `init`). See aeternity/aeternity#2619 for this.
The reason for this is to allow the compiler to decide the layout of the store. Currently it writes the entire state to state register 0, but in the future it can split up the state over multiple registers without requiring any changes to the VM.
=> PT-167701356 split store

rebar.config, rebar.lock, src/aeso_fcode_to_fate.erl
Minor change to reflect aeternity/aebytecode#66, which removes remote tail calls and adds an arity argument to normal remote calls.
=> Don't generate remote tail calls

priv/stdlib/List.aes
It was just a duplicated `filter`
=> Remove find_all from stdlib

rebar.config, rebar.lock, src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_ast_to_icode.erl, src/aeso_builtins.erl, src/aeso_errors.erl, src/aeso_fcode_to_fate.erl, test/aeso_compiler_tests.erl, test/contracts/bad_bytes_concat.aes, test/contracts/bad_bytes_split.aes, test/contracts/bytes_concat.aes
- Pivotal: [PT-168370742](https://www.pivotaltracker.com/story/show/168370742)
- aeternity/aebytecode#80
- aeternity/aeternity#2762
Adds
```
Bytes.concat : (bytes(A), bytes(B)) => bytes(A + B)
Bytes.split : bytes(A + B) => bytes(A) * bytes(B)
```
The type checker will solve for `A` and `B` and give an error message if they don't solve to concrete natural numbers.
=> Bytes.concat and Bytes.split

src/aeso_scan.erl, test/aeso_compiler_tests.erl, test/contracts/underscore_number_literals.aes
For instance, `1_000_000_000` or `#FFFF_FFFF_FFFF_FFFF`
=> Allow underscore separators in number and bytes literals

src/aeso_ast_infer_types.erl, test/aeso_compiler_tests.erl, test/contracts/contract_as_namespace.aes, test/contracts/multiple_contracts.aes
Previously the AEVM backend silently accepted defined functions in contract prototypes, but did the wrong thing, and the FATE backend crashed in code generation.
We could in principle allow defined functions in contract prototypes, but disallowing them makes it clear that no code is generated for the prototypes.
Also gives a type error if you try to call a function in another contract as if the contract were a namespace (i.e. `RemoteContract.some_fun(...)`). Previously this crashed during code generation.
=> Fail on defined functions in contract prototypes

src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_ast_to_icode.erl, src/aeso_fcode_to_fate.erl, src/aeso_parser.erl, src/aeso_pretty.erl, src/aeso_syntax.erl, src/aeso_syntax_utils.erl, test/aeso_compiler_tests.erl, test/aeso_parser_tests.erl, test/contracts/let_patterns.aes
Fixes #194 
~~Work-in-progress. Sits on top of #205.~~
Also adds pattern matching is list comprehension generators
```sophia
function somes(xs : list(option('a))) = [ x | Some(x) <- xs ]
```
Also also
- fix pattern matching on negative integers
- compile FATE values to immediates (e.g. `[1, 2, 3]` is compiled to `PUSH [1, 2, 3]` instead of a series of `CONS` instructions)
=> GH-194 let patterns

src/aeso_ast_infer_types.erl, src/aeso_compiler.erl, src/aeso_parser.erl
I have created and exposed some utility functions. I need to be able to pin into certain parts of the compiler for the purpose of my REPL.
Beside that I enchanted the way of running the parser – there is now a function `run_parser/{2,3}` which takes a parser `/0`, a string and optionally option list. Also, I added a `keep_included` option for the parser to report which files were included along with their hashes. This is useful when you want to keep track of which files are in context (I am using it in REPL to display warnings about duplicated includes for example)
=> Prepared for REPL usage

src/aeso_aci.erl, src/aeso_ast_infer_types.erl, src/aeso_compiler.erl, test/aeso_aci_tests.erl, test/aeso_compiler_tests.erl, test/contracts/hermetization_turnoff.aes
Added `debug_mode` option which exposes all functions in all namespaces and main contract to ease the process of unit testing. Meaning of this flag can be later extended to some additional features.
fixes #277
=> Debug mode to turn off hermetization

src/aeso_ast_infer_types.erl
It turned out that inner function clauses need to be hacked as well
=> Fix interface exposure (master)

src/aeso_ast_infer_types.erl, test/aeso_compiler_tests.erl, test/contracts/bad_state.aes
=> Properly handle type errors during desugar

docs/sophia_stdlib.md, priv/stdlib/List.aes
Complexity matters. This shamelessly stolen from [Haskell list library](https://hackage.haskell.org/package/base-4.14.1.0/docs/src/Data.OldList.html#sort) merge sort reduces gas usage by: 
* shit a lot on sorted lists
```
List.sort((a, b) => a < b, [1..50])
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
call gas: 212521
Sort.sort((a, b) => a < b, [1..50])
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
call gas: 6013
```
* shit a lot on reverse-sorted lists
```
List.sort((a, b) => a < b, …
```
=> Upgrade sorting function

docs/sophia.md
Note: `master` is targeted on purpose!
=> Add note about legacy (Lima) AENS pointers in update/lookup

CHANGELOG.md, docs/sophia_features.md, src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_parser.erl, src/aeso_pretty.erl, src/aeso_syntax.erl, src/aeso_syntax_utils.erl, test/aeso_compiler_tests.erl, test/contracts/assign_pattern_to_pattern.aes, test/contracts/assign_patterns.aes
Fixes #231
Examples of the new syntax can be found in the file `test/contracts/assign_patterns.aes`.
=> Allow assigning patterns to variables

CHANGELOG.md, src/aeso_aci.erl, src/aeso_ast_infer_types.erl, src/aeso_compiler.erl, src/aeso_errors.erl, src/aeso_parse_lib.erl, src/aeso_parser.erl, src/aeso_warnings.erl, test/aeso_compiler_tests.erl, test/contracts/warnings.aes
Currently added warnings:
Currently supported options:
Things that still need to be done:
Testing:
=> Add compiler warnings

src/aeso_ast_infer_types.erl, src/aeso_code_errors.erl, src/aeso_compiler.erl, src/aeso_errors.erl, test/aeso_abi_tests.erl, test/aeso_compiler_tests.erl
Fixes: #354
This PR changes most error messages to:
1. Remove formatting newlines (between sentences).
2. Remove trailing newlines (they will only show when print the error message using `aeso_errors:pp` but not in `#err.msg`).
3. Remove position info (e.g. `at line x, col y`) when it's already available from `#err.pos`.
4. Surround code with \` \` to make it distinguishable from the rest of the error message ("Unbound variable `x`", instead of "Unbound variable x").
=> Simplify error messages reported by the compiler

CHANGELOG.md, src/aeso_errors.erl
Some tools (and editors) prefer oneline error messages - so let's provide that in the simplest possible way.
=> Add oneline error pretty-printing

.github/workflows/requirements.txt
back then there was no official release of pygments that supported Sophia Syntax Highlighting
=> chore(deps): bump pygments version

docs/sophia_stdlib.md
I had to deal with `Set` recently and saw that it wasn't correctly placed in the `includable namespaces` section.
when fixing this I decided to sort everything alphabetically. makes sense IMO
=> docs: order namespaces alphabetically and place Set in includables

CHANGELOG.md, src/aeso_ast_to_fcode.erl, src/aeso_fcode_to_fate.erl
Fixes: #271 
The following options are introduced:
- `optimize_inliner`
- `optimize_inline_local_functions`
- `optimize_bind_subexpressions`
- `optimize_let_floating`
- `optimize_simplifier`
- `optimize_drop_unused_lets`
- `optimize_scode`
By default, all options are implicitly set to `true`, and they should be disabled separately by explicitly setting them to `false`.
=> Add options to enable/disable certain optimizations

CHANGELOG.md, docs/aeso_compiler.md, src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_compiler.erl, src/aeso_fcode_to_fate.erl
This PR will change the result of the compilation to include a mapping from variables to fate registers.
Code example:
```
contract X =
function g(z) =
let g = 1
g + z
entrypoint f() =
let g = g(5)
let h = g + 2
h + h
main contract C =
entrypoint f(x) =
let x = x + x
let y = x + x
let x = y + y
x + x
entrypoint g() =
let x = 3
x + x
entrypoint q(x) =
x + 1
stateful entrypoint xz() =
let aa : X = Chain.create()
aa.f()
```
Registers in the compilation result:
```
variables_registers =>
#{{"C","f","x"} => {var,2},
{"C","f","y"} => {var,1},
{"C","g","x"} => {var,0},
{"C","q","x"} => {arg,0},
{"C","x","a"} => {var,0},
{"X",".X.g","g"} => {var,0},
{"X",".X.g","z"} => {arg,0},
{"X","f","g"} => {var,0},
{"X","f","h"} => {var,1}},
```
=> Return mapping from variables to registers in fate compilation

CHANGELOG.md, docs/aeso_aci.md, src/aeso_aci.erl, test/aeso_aci_tests.erl
related to https://github.com/aeternity/aepp-sdk-js/issues/1681
Also, it would be consistent with `typedef` that appears in the source code.
=> Rename `type_defs` to `typedefs` in ACI to increase compatibility

.github/workflows/requirements.txt
@ghallak @hanssv I am sorry but I probably didn't check the dependency on pygments with last PR
```
ERROR: Cannot install -r .github/workflows/requirements.txt (line 3) and pygments==2.12.0 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested pygments==2.12.0
mkdocs-material 9.0.9 depends on pygments>=2.14
```
this should be fixed now
=> fix: use latest pygments version to generate docs

docs/sophia_stdlib.md
=> [Ceres]: document changes to Auth.tx_hash

CHANGELOG.md, docs/sophia_stdlib.md, priv/stdlib/String.aes, rebar.config, src/aeso_aci.erl, src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_fcode_to_fate.erl, src/aeso_parser.erl, src/aeso_pretty.erl, test/aeso_compiler_tests.erl, test/contracts/bad_bytes_to_x.aes, test/contracts/bytes_misc.aes, test/contracts/bytes_to_x.aes
Introduce arbitrary sized binary arrays (type `bytes()`); adding `Bytes.split_any`, `Bytes.to_fixed_size`, `Bytes.to_any_size`, `Bytes.size`, `String.to_bytes`, and `Int.to_bytes`; and adjust `Bytes.concat` to allow both fixed and arbitrary sized byte arrays.
=> Add arbitrary size byte arrays

CHANGELOG.md, src/aeso_ast_infer_types.erl, test/aeso_compiler_tests.erl
This PR should prevent this code from compiling
```
include "Frac.aes"
contract interface Interface =
entrypoint example: (Frac.frac) => Frac.frac
main contract Example: Interface =
entrypoint example(x : int): int = x
```
=> Unify typesigs when implementing interface funs

src/aeso_ast_infer_types.erl
Fingers itched... This solves one actual problem (on Ceres branch once rebased) where three constraints depended on each other and the current implementation only made two iterations.
The rewrite should be more general and easier to further change if necessary. Would be nice to separate solving and error reporting further - but lets save that for another rainy day.
=> Improve constraint solving

CHANGELOG.md, src/aeso_fcode_to_fate.erl
There is an omission in the logic checking whether two byte code instructions are independent - as demonstrated by #482 
This adds a check that an instruction reading the store/state is not pushed past an impure instruction (for example a function call).
This results in:
```
FUNCTION foo( integer) : integer
;; BB : 0
MAP_LOOKUP var0 store1 arg0
PUSH arg0
CALL "IBB"
;; BB : 1
POP var9999
RETURNR var0
```
Fixes #482 
=> Improve independence analysis in code optimizer

CHANGELOG.md, src/aeso_ast_infer_types.erl, src/aeso_syntax_utils.erl
Allow referring to `foo` in namespace `X` as `X.foo` when already inside `X`. 
This used to result in an error if dependencies happened to be analyzed in the wrong order...
This PR is supported by Æternity Foundation.
=> Allow self-qualification

CHANGELOG.md, priv/stdlib/List.aes, src/aeso_parser.erl, src/aeso_pretty.erl
In OTP-27 else is made a keyword, so needs to be 'else'.
This PR is supported by Æternity Foundation.
=> Fix parser/pretty printer for OTP-27 

CHANGELOG.md, docs/sophia_features.md, docs/sophia_syntax.md, src/aeso_aci.erl, src/aeso_ast_infer_types.erl, src/aeso_ast_to_fcode.erl, src/aeso_compiler.erl, src/aeso_fcode_to_fate.erl, src/aeso_parser.erl, src/aeso_pretty.erl, src/aeso_syntax.erl, src/aeso_vm_decode.erl, test/aeso_calldata_tests.erl, test/aeso_encode_decode_tests.erl, test/contracts/ceres.aes, test/contracts/funargs.aes
Add signature literal `sg_...` + handle system alias types (hash, unit, signature) explicitly when converting to Sophia values. This makes it possible to return `sg_...` if the type is `signature` despite type inference being made with `bytes(64)`.
=> Add signature literals

docs/sophia_stdlib.md
Otherwise I'm getting error
> Invalid type `()`. The syntax of tuple types changed in Sophia version 4.0. Did you mean `unit`
This PR is supported by the Æternity Foundation
=> Docs: Fix return value type in Auction example

docs/sophia_stdlib.md
This PR is supported by the Æternity Foundation
=> Docs: Move `poseidon` outside of `create`

docs/sophia_features.md, docs/sophia_stdlib.md, src/aeso_ast_infer_types.erl
* Add `char` to the list of Sophia types
* Move `Chain.ttl` to stdlib docs instead of Sophia types
* Add a note about `Chain.ttl` being a special case
* Make `Call.gas_left` a constant instead of a zero-argument function
* Move the function `Int.mulmod` to its right place in stdlib docs
* Move the function `Crypto.poseidon` to its right place in stdlib docs
* Fix typos in 'sophia_stdlib.md'
* Add `bytes_t` to `utype()` in the type checker
=> Update the docs
